<?php

declare(strict_types=1);

namespace App\Domain\Clinical\Http\Resources;

use App\Domain\Clinical\Models\SessionVital;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property-read SessionVital $resource
 */
final class SessionVitalResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'recorded_at' => $this->resource->recorded_at->toIso8601String(),
            'minutes_elapsed' => $this->resource->minutes_elapsed,
            'bp_sys' => $this->resource->bp_sys,
            'bp_dia' => $this->resource->bp_dia,
            // Generated by MySQL: dia + (sys - dia)/3.
            'map_mmhg' => $this->resource->map_mmhg,
            'pulse' => $this->resource->pulse,
            'temp_c' => $this->resource->temp_c,
            'spo2_pct' => $this->resource->spo2_pct,
            'blood_flow_ml_min' => $this->resource->blood_flow_ml_min,
            'arterial_pressure_mmhg' => $this->resource->arterial_pressure_mmhg,
            'venous_pressure_mmhg' => $this->resource->venous_pressure_mmhg,
            'tmp_mmhg' => $this->resource->tmp_mmhg,
            'uf_rate_ml_hr' => $this->resource->uf_rate_ml_hr,
            'uf_volume_ml' => $this->resource->uf_volume_ml,
            'rbv_pct' => $this->resource->rbv_pct,
            'heparin_given' => $this->resource->heparin_given,
            'comment' => $this->resource->comment,
            'source' => $this->resource->source,
        ];
    }
}
