<?php

declare(strict_types=1);

namespace App\Domain\Clinical\Http\Resources;

use App\Domain\Clinical\Adequacy;
use App\Domain\Clinical\Models\TreatmentSession;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property-read TreatmentSession $resource
 */
final class TreatmentSessionResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        $session = $this->resource;

        return [
            'public_id' => $session->public_id,
            'session_date' => $session->session_date->toDateString(),
            'status' => $session->status->value,
            'modality' => $session->modality,

            // Locked is the fact a client actually needs: it decides whether the
            // flow sheet is still writable or whether a correction has to go
            // through the amendment path.
            'is_locked' => $session->isLocked(),
            'locked_at' => $session->locked_at?->toIso8601String(),
            'nurse_signed_at' => $session->nurse_signed_at?->toIso8601String(),
            'physician_signed_at' => $session->physician_signed_at?->toIso8601String(),

            'checked_in_at' => $session->checked_in_at?->toIso8601String(),
            'started_at' => $session->started_at?->toIso8601String(),
            'ended_at' => $session->ended_at?->toIso8601String(),
            // Generated by MySQL from started_at/ended_at.
            'actual_duration_min' => $session->actual_duration_min,

            'pre_weight_kg' => $session->pre_weight_kg,
            'dry_weight_kg' => $session->dry_weight_kg,
            'post_weight_kg' => $session->post_weight_kg,
            // Both generated: pre - dry, and pre - post.
            'idwg_kg' => $session->idwg_kg,
            'weight_loss_kg' => $session->weight_loss_kg,

            'planned_duration_min' => $session->planned_duration_min,
            'planned_uf_ml' => $session->planned_uf_ml,
            'net_uf_ml' => $session->net_uf_ml,

            'ktv' => $session->ktv,
            'urr_pct' => $session->urr_pct,
            'termination_reason' => $session->termination_reason,

            // Measured against published targets rather than left for the client
            // to know. The thresholds live in one place server-side, so a screen
            // cannot quietly disagree about what "adequate" means.
            'adequacy' => $this->adequacy($session),

            'patient' => [
                'public_id' => $session->patient?->public_id,
                'mrn' => $session->patient?->mrn,
                'full_name' => $session->patient?->full_name,
            ],
        ];
    }

    /**
     * Adequacy against target, and the fluid-removal rate.
     *
     * The UF rate is computed on read rather than stored: it is a pure function
     * of three columns already on the row, and a stored copy is one more thing
     * that can disagree with them.
     *
     * @return array<string, mixed>
     */
    private function adequacy(TreatmentSession $session): array
    {
        $ktv = $session->ktv === null ? null : (float) $session->ktv;
        $urr = $session->urr_pct === null ? null : (float) $session->urr_pct;

        $ufRate = null;

        if (
            $session->net_uf_ml !== null
            && $session->dry_weight_kg !== null
            && (float) $session->dry_weight_kg > 0
            && $session->getAttribute('actual_duration_min') !== null
            && (int) $session->actual_duration_min > 0
        ) {
            $ufRate = Adequacy::ufRateMlPerKgPerHour(
                (float) $session->net_uf_ml,
                (float) $session->dry_weight_kg,
                (int) $session->actual_duration_min / 60,
            );
        }

        return [
            'ktv_target' => Adequacy::KTV_TARGET,
            'ktv_meets_target' => $ktv === null ? null : Adequacy::ktvMeetsTarget($ktv),
            'urr_target_pct' => Adequacy::URR_TARGET_PCT,
            'urr_meets_target' => $urr === null ? null : Adequacy::urrMeetsTarget($urr),
            'uf_rate_ml_kg_h' => $ufRate,
            'uf_rate_limit_ml_kg_h' => Adequacy::UF_RATE_CONCERN_ML_KG_H,
            // Flythe 2011: sustained rates above the limit carry excess
            // cardiovascular mortality. Reported, never blocked -- the fluid had
            // to come off, and the answer is a longer session, not a refusal.
            'uf_rate_of_concern' => $ufRate === null ? null : Adequacy::ufRateIsOfConcern($ufRate),
        ];
    }
}
