<?php

declare(strict_types=1);

use App\Domain\Core\Models\Patient;
use App\Domain\Core\Models\Staff;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/*
|--------------------------------------------------------------------------
| Patient registry
|--------------------------------------------------------------------------
| Phase 1. The rules worth testing here are the ones the database cannot hold:
| MySQL CHECK constraints may not call CURRENT_DATE, so "a birth date is not in
| the future" has to be enforced in PHP or not at all. And a status change that
| leaves no history row is a chart that cannot answer "when did this patient
| transfer out?" three years later.
*/

uses(TestCase::class, RefreshDatabase::class);

function registrar(): Staff
{
    return staffWithRole('records');
}

/** @return array<string, mixed> */
function patientPayload(array $overrides = []): array
{
    return array_merge([
        'mrn' => 'MRN-40001',
        'first_name' => 'Amihan',
        'last_name' => 'Bautista',
        'birth_date' => '1968-04-11',
        'sex' => 'female',
    ], $overrides);
}

it('registers a patient and opens the status history in the same breath', function () {
    $response = $this->actingAs(registrar(), 'sanctum')
        ->postJson('/api/v1/patients', patientPayload());

    // 201: Laravel returns Created when a POST returns a resource for a
    // freshly created model.
    $response->assertCreated()
        ->assertJsonPath('mrn', 'MRN-40001')
        ->assertJsonPath('status', 'active')
        // full_name is generated by MySQL, never written by Eloquent.
        ->assertJsonPath('full_name', 'Amihan Bautista');

    $patient = Patient::query()->where('mrn', 'MRN-40001')->firstOrFail();

    expect(DB::table('patient_status_histories')->where('patient_id', $patient->id)->count())->toBe(1)
        ->and(DB::table('patient_status_histories')->where('patient_id', $patient->id)->value('status'))->toBe('active');
});

it('refuses a birth date in the future', function () {
    // MySQL cannot express this: CHECK may not call CURRENT_DATE. If the
    // FormRequest stops enforcing it, nothing else will.
    $this->actingAs(registrar(), 'sanctum')
        ->postJson('/api/v1/patients', patientPayload([
            'birth_date' => now()->addDay()->toDateString(),
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('birth_date');

    expect(Patient::query()->count())->toBe(0);
});

it('refuses a duplicate MRN', function () {
    $registrar = registrar();

    $this->actingAs($registrar, 'sanctum')->postJson('/api/v1/patients', patientPayload())->assertCreated();

    $this->actingAs($registrar, 'sanctum')
        ->postJson('/api/v1/patients', patientPayload(['first_name' => 'Someone else']))
        ->assertStatus(422)
        ->assertJsonValidationErrors('mrn');

    expect(Patient::query()->count())->toBe(1);
});

it('will not let a nurse register a patient', function () {
    // Registration is a records function. PatientPolicy::create says so.
    $this->actingAs(staffWithRole('nurse'), 'sanctum')
        ->postJson('/api/v1/patients', patientPayload())
        ->assertForbidden();

    expect(Patient::query()->count())->toBe(0);
});

it('records a status change against the history, not just the column', function () {
    $patient = Patient::factory()->create(['status' => 'active']);

    $this->actingAs(registrar(), 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/status", [
            'status' => 'transferred_out',
            'effective_on' => now()->subDays(3)->toDateString(),
            'reason' => 'moved province',
            'destination' => 'Cebu Renal Centre',
        ])
        ->assertOk()
        ->assertJsonPath('status', 'transferred_out');

    $history = DB::table('patient_status_histories')->where('patient_id', $patient->id)->latest('id')->first();

    expect($history->status)->toBe('transferred_out')
        ->and($history->destination)->toBe('Cebu Renal Centre')
        ->and($history->effective_on)->toBe(now()->subDays(3)->toDateString())
        ->and($patient->fresh()->status_changed_on->toDateString())->toBe(now()->subDays(3)->toDateString());
});

it('will not backdate a status change into the future', function () {
    $patient = Patient::factory()->create();

    $this->actingAs(registrar(), 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/status", [
            'status' => 'on_hold',
            'effective_on' => now()->addWeek()->toDateString(),
        ])
        ->assertStatus(422)
        ->assertJsonValidationErrors('effective_on');
});

it('will not silently reactivate a patient who was transferred out', function () {
    $patient = Patient::factory()->create(['status' => 'transferred_out']);

    $this->actingAs(registrar(), 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/status", [
            'status' => 'active',
            'effective_on' => now()->toDateString(),
        ])
        // 422, not 500: the rule refused the request, nothing broke.
        ->assertStatus(422);

    expect($patient->fresh()->status)->toBe('transferred_out');

    // With a reason on the record, it goes through.
    $this->actingAs(registrar(), 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/status", [
            'status' => 'active',
            'effective_on' => now()->toDateString(),
            'reason' => 'returned to the area, restarting here',
        ])
        ->assertOk();

    expect($patient->fresh()->status)->toBe('active');
});

it('does not let a demographic update change the status', function () {
    $patient = Patient::factory()->create(['status' => 'active']);

    $this->actingAs(registrar(), 'sanctum')
        ->patchJson("/api/v1/patients/{$patient->public_id}", [
            'last_name' => 'Corrected',
            'status' => 'deceased',
        ])
        ->assertOk()
        ->assertJsonPath('last_name', 'Corrected');

    // The status is stripped by the service; changing it needs the status
    // endpoint, which writes a history row.
    expect($patient->fresh()->status)->toBe('active')
        ->and(DB::table('patient_status_histories')->where('patient_id', $patient->id)->count())->toBe(0);
});

it('soft deletes a patient and never removes the row', function () {
    $patient = Patient::factory()->create();

    $this->actingAs(staffWithRole('admin'), 'sanctum')
        ->deleteJson("/api/v1/patients/{$patient->public_id}")
        ->assertNoContent();

    expect(Patient::query()->count())->toBe(0)
        ->and(Patient::withTrashed()->count())->toBe(1)
        ->and(DB::table('patients')->where('id', $patient->id)->exists())->toBeTrue();
});

it('will not let a records officer delete a patient', function () {
    $patient = Patient::factory()->create();

    $this->actingAs(registrar(), 'sanctum')
        ->deleteJson("/api/v1/patients/{$patient->public_id}")
        ->assertForbidden();

    expect(Patient::query()->count())->toBe(1);
});

it('returns the paginator envelope the typed client expects', function () {
    // packages/api-client parses this shape with Zod. If Laravel's envelope
    // changes -- or someone turns wrapping off for collections too -- the client
    // starts throwing at runtime, so the contract is pinned here.
    Patient::factory()->count(3)->create();

    $body = $this->actingAs(staffWithRole('nurse'), 'sanctum')
        ->getJson('/api/v1/patients?per_page=2')
        ->assertOk()
        ->json();

    expect($body)->toHaveKeys(['data', 'links', 'meta'])
        ->and($body['data'])->toHaveCount(2)
        ->and($body['meta']['total'])->toBe(3)
        ->and($body['meta']['per_page'])->toBe(2)
        ->and($body['meta'])->toHaveKeys(['current_page', 'last_page', 'per_page', 'total'])
        // Still no internal id, even in a list.
        ->and($body['data'][0])->not->toHaveKey('id');
});

it('searches by MRN and surname', function () {
    Patient::factory()->create(['mrn' => 'MRN-77001', 'last_name' => 'Villanueva']);
    Patient::factory()->create(['mrn' => 'MRN-77002', 'last_name' => 'Reyes']);

    $nurse = staffWithRole('nurse');

    $byMrn = $this->actingAs($nurse, 'sanctum')->getJson('/api/v1/patients?search=MRN-77001')->assertOk()->json('data');
    $byName = $this->actingAs($nurse, 'sanctum')->getJson('/api/v1/patients?search=Villan')->assertOk()->json('data');

    expect($byMrn)->toHaveCount(1)
        ->and($byMrn[0]['mrn'])->toBe('MRN-77001')
        ->and($byName)->toHaveCount(1)
        ->and($byName[0]['last_name'])->toBe('Villanueva');
});

it('keeps dry weight as an effective-dated history, not a mutable column', function () {
    $patient = Patient::factory()->create();
    $nephrologist = staffWithRole('nephrologist');

    $this->actingAs($nephrologist, 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/dry-weights", [
            'weight_kg' => '57.50',
            'effective_from' => now()->subMonths(2)->toDateString(),
            'reason' => 'initial assessment',
        ])
        ->assertCreated();

    $this->actingAs($nephrologist, 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/dry-weights", [
            'weight_kg' => '56.00',
            'effective_from' => now()->toDateString(),
            'reason' => 'persistent hypotension',
        ])
        ->assertCreated();

    $body = $this->actingAs($nephrologist, 'sanctum')
        ->getJson("/api/v1/patients/{$patient->public_id}/dry-weights")
        ->assertOk()
        ->json();

    // The current target is today's revision, and BOTH rows survive: a session
    // run two months ago is still interpretable against the 57.50 that was in
    // force then. That is the whole point of not making this a column.
    expect($body['current_kg'])->toBe('56.00')
        ->and($body['history'])->toHaveCount(2);

    expect(DB::table('dry_weights')->where('patient_id', $patient->id)->count())->toBe(2);
});

it('rejects a dry weight outside the range the database will accept', function () {
    $patient = Patient::factory()->create();

    $this->actingAs(staffWithRole('nephrologist'), 'sanctum')
        ->postJson("/api/v1/patients/{$patient->public_id}/dry-weights", [
            'weight_kg' => '4.00',
            'effective_from' => now()->toDateString(),
        ])
        ->assertStatus(422)
        ->assertJsonValidationErrors('weight_kg');
});
