<?php

declare(strict_types=1);

namespace App\Domain\Billing\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use stdClass;

/**
 * One row of the invoices list. See ClaimSummaryResource for why it is a
 * resource and not the raw row.
 *
 * @property stdClass $resource
 */
final class InvoiceSummaryResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        $row = $this->resource;

        return [
            'invoice_no' => $row->invoice_no,
            'issued_on' => (string) $row->issued_on,
            'status' => $row->status,
            'currency' => $row->currency,
            'patient' => [
                'public_id' => $row->patient_public_id,
                'mrn' => $row->mrn,
                'full_name' => $row->full_name,
            ],
            // Money stays a string; balance is generated by MySQL.
            'subtotal' => $row->subtotal,
            'payer_covered' => $row->payer_covered,
            'patient_due' => $row->patient_due,
            'amount_paid' => $row->amount_paid,
            'balance' => $row->balance,
        ];
    }
}
