<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Domain\Core\Models\Staff;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

/**
 * @extends Factory<Staff>
 */
final class StaffFactory extends Factory
{
    protected $model = Staff::class;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'employee_no' => 'EMP-'.$this->faker->unique()->numberBetween(1000, 9999),
            'first_name' => $this->faker->firstName(),
            'last_name' => $this->faker->lastName(),
            'email' => $this->faker->unique()->safeEmail(),
            'password' => Hash::make('password'),
            'clinical_pin_hash' => Hash::make('123456'),
            'is_active' => true,
            // full_name is generated by MySQL.
        ];
    }

    /**
     * Grant a role. The role must already exist in `roles`, which the reference
     * seed loads -- inventing a role code here would let a test pass against a
     * permission the real system does not have.
     */
    public function withRole(string $roleCode): self
    {
        return $this->afterCreating(function (Staff $staff) use ($roleCode): void {
            DB::table('role_staff')->insertOrIgnore([
                'staff_id' => $staff->id,
                'role_code' => $roleCode,
                'granted_at' => now(),
            ]);
        });
    }

    public function inactive(): self
    {
        return $this->state(fn (): array => ['is_active' => false]);
    }
}
